services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data

  backend:
    image: todo-backend
    container_name: backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongo
      - redis

  frontend:
    image: todo-frontend
    container_name: frontend-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend

  debug-helper:
    image: busybox
    container_name: debug-helper
