POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "id": "abdcdef0-1234-5678-9abc-def87654321",
  "type": "HealthCheck",
  "date": "2025-03-03",
  "description": "Patient has been feeling a bit under the weather lately. No major issues, just a general check-up.",
  "specialist": "Dr. Smith",
  "diagnosisCodes": [
      "H35.29",
      "H54.7",
      "F43.2"
  ],
  "healthCheckRating": 2
}