# Use an official Node.js runtime as a parent image
FROM node:22 AS build-stage

# Set the working directory
WORKDIR /usr/src/app

# Copy the the application code
COPY . .

# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 3001

# Run the application in development mode
CMD ["npm", "run", "docker:dev"]